USE MASTER;
IF EXISTS (SELECT * FROM sys.databases WHERE NAME='BDDCURSO_0')
	DROP DATABASE BDDCURSO_0
CREATE DATABASE BDDCURSO_0
-- setting database path files default
USE MASTER;
IF EXISTS (SELECT * FROM sys.databases WHERE name='BDDCURSO_0')
	DROP DATABASE BDDCURSO_0;
CREATE DATABASE BDDCURSO_0
ON (
	NAME=BDDCURSO_0,
	FILENAME='C:\cursos\sql\BDDCURSO_0.mdf'
)
LOG ON (
	NAME=BDDCURSO_0_log,
	FILENAME='C:\cursos\sql\BDDCURSO_0_log.ldf'
)